language: java
dist: trusty
jdk: openjdk11
env:
  global:
  - ANDROID_SDK_CMD_TOOLS=commandlinetools-linux-7583922_latest.zip
  - SERVICE_ACCOUNT_FILE=./google_service_account.json
  - BUNDLE_LOCATION=./app/build/outputs/bundle/release/app-release.aab
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache/"
before_install:
- wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_CMD_TOOLS
- mkdir -p $HOME/sdk/cmdline-tools && unzip -q $ANDROID_SDK_CMD_TOOLS -d $HOME/sdk/cmdline-tools
- mv $HOME/sdk/cmdline-tools/cmdline-tools $HOME/sdk/cmdline-tools/latest
- export PATH=$PATH:$HOME/sdk/cmdline-tools/latest/bin
- export ANDROID_SDK_ROOT=$HOME/sdk
- mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
- openssl aes-256-cbc -K $encrypted_fb5491918f57_key -iv $encrypted_fb5491918f57_iv
  -in vmenon_keystore.enc -out vmenon_keystore -d
- openssl aes-256-cbc -K $encrypted_faf62aa3591f_key -iv $encrypted_faf62aa3591f_iv
  -in google_service_account.json.enc -out google_service_account.json -d
install:
- yes | sdkmanager --licenses >/dev/null
before_script:
- chmod +x gradlew
- mkdir -p $HOME/.gradle
- echo "org.gradle.daemon=false" >> $HOME/.gradle/gradle.properties
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
- rm -f $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- rm -f $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
- rm -f $HOME/.gradle/caches/*/javaCompile/javaCompile.lock
- rm -f $HOME/.gradle/caches/*/executionHistory/executionHistory.bin
- rm -f $HOME/.gradle/caches/*/executionHistory/executionHistory.lock
- rm -f $HOME/.gradle/caches/journal-1/file-access.bin
- rm -f $HOME/.gradle/caches/journal-1/journal-1.lock
- rm -f $HOME/.gradle/caches/transforms-1/transforms-1.lock
- rm -f $HOME/.gradle/caches/user-id.txt.lock
- ls -d $HOME/.gradle/wrapper/dists/* -1t | tail -n +2 | xargs rm -rf
script:
- "./gradlew test lint :app:bundleRelease"
after_success:
- "./uploadBundle.sh"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: oOc4FkirP5t6VELPc4bXbOs8fdFpQ6+lpOwIokrByKKqbLzXd8hmoSehczDrd4AXEBIMFs/ztRbq0n2hyzKK43Wvl3Pu3tMx6/eo+ZX/L+0MdvwNvEc2DH+nJvXHqhaCPeYV/b+YXF5bYAj4DjpSjSTOipwwFwComgzAmTSoyscQEgSB1KlqOTeAoc0CLhtRv/Wvgb+reD4Z2+X26unyEk3ExCHTUJhMULtzS0rZHOJvv9CePu5IuzJeGy1o3CGAB1yKH05sVoMZRoMYWsMNk8ME3EZbbvAzOFEF3XFTL+HYCCh1lcMoLpHR42BnROqXKWoflTdE2hTuz7FKHDs2Tn3fRBuo+/6EWwFUoL24KC+pcNn0uzSWC0xrgdeEZvFAZ6vE0sAvnJzGDgcj9Wtq99zcDLQSqFPa0u8T5ISpcOMvnanzMChfAxW1BDSX417rEy6bFnVGB543fnwVRUXIlnEvZYcnfcXkyt9YwFm91Dsijb7eJjgsYc0a5x3c8c3Ay6S796ejZS6xira6lxFQjbCMhrzdZ7PkllKbeY6cpqHS3sgvVBMj80rJ5pysy/HhiSGjAOiGDFkZzlcEtl/wQKNPPnrNOFaMlmrKom1ootpCM85/0cKTHXaNVIB4Ih+hoW2pgI3wuMaDizIpwpHM4kEKsaKUhdVFx1eGYAkUX6s=
  file_glob: true
  file: "/home/travis/build/hitoshura25/Media-Player-Omega-Android/app/build/outputs/bundle/release/*"
  on:
    repo: hitoshura25/Media-Player-Omega-Android
    tags: true