language: android
dist: trusty
jdk: oraclejdk11
env:
  global:
    # for updates check https://developer.android.com/studio#downloads
    - ANDROID_SDK_CMD_TOOLS=commandlinetools-linux-7583922_latest.zip
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-30.0.2
  - android-30
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-x86-android-30
  - sys-img-armeabi-v7a-android-17
before_install:
  # download and unzip Android SDK command line tools
  - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_CMD_TOOLS
  - mkdir -p $HOME/sdk/cmdline-tools && unzip -q $ANDROID_SDK_CMD_TOOLS -d $HOME/sdk/cmdline-tools
  - mv $HOME/sdk/cmdline-tools/cmdline-tools $HOME/sdk/cmdline-tools/latest
  # set SDK tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/cmdline-tools/latest/bin
  - export ANDROID_SDK_ROOT=$HOME/sdk
  # create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
  - openssl aes-256-cbc -K $encrypted_fb5491918f57_key -iv $encrypted_fb5491918f57_iv -in vmenon_keystore.enc -out vmenon_keystore -d
install:
  # accept licenses for all available packages that have not already been accepted
  - yes | sdkmanager --licenses >/dev/null
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: "oOc4FkirP5t6VELPc4bXbOs8fdFpQ6+lpOwIokrByKKqbLzXd8hmoSehczDrd4AXEBIMFs/ztRbq0n2hyzKK43Wvl3Pu3tMx6/eo+ZX/L+0MdvwNvEc2DH+nJvXHqhaCPeYV/b+YXF5bYAj4DjpSjSTOipwwFwComgzAmTSoyscQEgSB1KlqOTeAoc0CLhtRv/Wvgb+reD4Z2+X26unyEk3ExCHTUJhMULtzS0rZHOJvv9CePu5IuzJeGy1o3CGAB1yKH05sVoMZRoMYWsMNk8ME3EZbbvAzOFEF3XFTL+HYCCh1lcMoLpHR42BnROqXKWoflTdE2hTuz7FKHDs2Tn3fRBuo+/6EWwFUoL24KC+pcNn0uzSWC0xrgdeEZvFAZ6vE0sAvnJzGDgcj9Wtq99zcDLQSqFPa0u8T5ISpcOMvnanzMChfAxW1BDSX417rEy6bFnVGB543fnwVRUXIlnEvZYcnfcXkyt9YwFm91Dsijb7eJjgsYc0a5x3c8c3Ay6S796ejZS6xira6lxFQjbCMhrzdZ7PkllKbeY6cpqHS3sgvVBMj80rJ5pysy/HhiSGjAOiGDFkZzlcEtl/wQKNPPnrNOFaMlmrKom1ootpCM85/0cKTHXaNVIB4Ih+hoW2pgI3wuMaDizIpwpHM4kEKsaKUhdVFx1eGYAkUX6s="
  file_glob: true
  file: /home/travis/build/hitoshura25/Media-Player-Omega-Android/app/build/outputs/bundle/release/*
  on:
    repo: hitoshura25/Media-Player-Omega-Android
    tags: true