# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@1.0.3

parameters:
  run_workflow_feature_build:
    default: true
    type: boolean

  run_workflow_release:
    default: false
    type: boolean

  release_version_increment:
    default: patch
    type: string

commands:
  update_bundler:
    steps:
      - run: gem install bundler
      - run: bundle check || bundle install --path vendor/bundle
  create_gradle_cache_key:
    steps:
      - run:
          name: Hash gradle dependency info
          command: |
            md5sum gradle/wrapper/gradle-wrapper.properties appVersion.properties versions.properties gradle.properties settings.gradle build.gradle **/*build.gradle > /tmp/gradle_deps.md5
  restore_gem_cache:
    steps:
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: gradle-{{ checksum "/tmp/gradle_deps.md5" }}
  save_gem_cache:
    steps:
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  save_gradle_cache:
    steps:
      - save_cache:
          key: gradle-{{ checksum "/tmp/gradle_deps.md5" }}
          paths:
            - ~/.gradle
jobs:
  build-feature:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - restore_gem_cache
      - create_gradle_cache_key
      - restore_gradle_cache
      - update_bundler
      - save_gem_cache
      # The next step will run the unit tests
      #- android/run-tests:
      #    test-command: ./gradlew lint testDebug --continue

      # Then start the emulator and run the Instrumentation tests!
      - android/start-emulator-and-run-tests:
          post-emulator-launch-assemble-command: ./prepareForInstrumentationTests.sh
          test-command: ./runInstrumentationTests.sh
          system-image: system-images;android-31;google_apis;x86
      - run:
          name: Build Feature
          command: ./buildFeature.sh
      - save_gradle_cache
  release:
    parameters:
      release_version_increment:
        type: string
    executor:
      name: android/android-machine
    steps:
      - checkout
      - restore_gem_cache
      - create_gradle_cache_key
      - restore_gradle_cache
      - run: git config --global user.email "circleci@circleci"
      - run: git config --global user.name "Circle CI"
      - update_bundler
      - save_gem_cache
      - run:
          name: Release
          command: |
            ./incrementVersion.sh << parameters.release_version_increment >>
  deploy_release:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - restore_gem_cache
      - create_gradle_cache_key
      - restore_gradle_cache
      - update_bundler
      - save_gem_cache
      - run:
          name: Release
          command: |
            ./release.sh
      - save_gradle_cache
workflows:
  feature_build:
    when: << pipeline.parameters.run_workflow_feature_build >>
    jobs:
      - build-feature:
          filters:
            branches:
              ignore: main
  release:
    when: << pipeline.parameters.run_workflow_release >>
    jobs:
      - release:
          release_version_increment: << pipeline.parameters.release_version_increment >>
          filters:
            branches:
              only: main
  ci_release:
    jobs:
      - release:
          release_version_increment: ci
          filters:
            branches:
              only: main
  deploy_release:
    jobs:
      - deploy_release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
