import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * https://developer.android.com/jetpack/androidx/releases/appcompat#1.3.0
   */
  const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val cardview: String = "androidx.cardview:cardview:" + Versions.cardview

  /**
   * http://tools.android.com
   */
  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
      Versions.constraintlayout

  /**
   * https://developer.android.com/jetpack/androidx/releases/core#1.5.0
   */
  const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

  /**
   * https://developer.android.com/jetpack/androidx/releases/fragment#1.3.4
   */
  const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:" +
      Versions.legacy_support_v4

  /**
   * https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.1
   */
  const val lifecycle_common_java8: String = "androidx.lifecycle:lifecycle-common-java8:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.1
   */
  const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.1
   */
  const val lifecycle_process: String = "androidx.lifecycle:lifecycle-process:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.1
   */
  const val lifecycle_reactivestreams_ktx: String =
      "androidx.lifecycle:lifecycle-reactivestreams-ktx:" + Versions.androidx_lifecycle

  /**
   * https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.1
   */
  const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.1
   */
  const val lifecycle_service: String = "androidx.lifecycle:lifecycle-service:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/jetpack/androidx/releases/lifecycle#2.3.1
   */
  const val lifecycle_viewmodel_ktx: String = "androidx.lifecycle:lifecycle-viewmodel-ktx:" +
      Versions.androidx_lifecycle

  /**
   * https://developer.android.com/jetpack/androidx/releases/media#1.3.1
   */
  const val androidx_media_media: String = "androidx.media:media:" + Versions.androidx_media_media

  const val multidex_instrumentation: String = "androidx.multidex:multidex-instrumentation:" +
      Versions.androidx_multidex

  const val androidx_multidex_multidex: String = "androidx.multidex:multidex:" +
      Versions.androidx_multidex

  /**
   * https://developer.android.com/jetpack/androidx/releases/recyclerview#1.2.0
   */
  const val recyclerview: String = "androidx.recyclerview:recyclerview:" + Versions.recyclerview

  /**
   * https://developer.android.com/jetpack/androidx/releases/room#2.3.0
   */
  const val room_compiler: String = "androidx.room:room-compiler:" + Versions.androidx_room

  /**
   * https://developer.android.com/jetpack/androidx/releases/room#2.3.0
   */
  const val room_ktx: String = "androidx.room:room-ktx:" + Versions.androidx_room

  /**
   * https://developer.android.com/jetpack/androidx/releases/room#2.3.0
   */
  const val room_runtime: String = "androidx.room:room-runtime:" + Versions.androidx_room

  /**
   * https://developer.android.com/jetpack/androidx/releases/room#2.3.0
   */
  const val room_rxjava2: String = "androidx.room:room-rxjava2:" + Versions.androidx_room

  /**
   * https://developer.android.com/jetpack/androidx/releases/room#2.3.0
   */
  const val room_testing: String = "androidx.room:room-testing:" + Versions.androidx_room

  /**
   * https://developer.android.com/testing
   */
  const val espresso_core: String = "androidx.test.espresso:espresso-core:" + Versions.espresso_core

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_ext_junit: String = "androidx.test.ext:junit:" +
      Versions.androidx_test_ext_junit

  /**
   * https://developer.android.com/jetpack/androidx/releases/work#2.5.0
   */
  const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:" + Versions.work_runtime_ktx

  const val com_android_support_multidex: String = "com.android.support:multidex:" +
      Versions.com_android_support_multidex

  /**
   * http://tools.android.com/
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  /**
   * http://tools.android.com/
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  /**
   * https://github.com/facebook/stetho
   */
  const val stetho: String = "com.facebook.stetho:stetho:" + Versions.stetho

  /**
   * https://github.com/bumptech/glide
   */
  const val glide: String = "com.github.bumptech.glide:glide:" + Versions.glide

  const val exoplayer_core: String = "com.google.android.exoplayer:exoplayer-core:" +
      Versions.exoplayer_core

  /**
   * https://github.com/material-components/material-components-android
   */
  const val material: String = "com.google.android.material:material:" + Versions.material

  /**
   * https://github.com/google/gson
   */
  const val gson: String = "com.google.code.gson:gson:" + Versions.gson

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android_processor: String = "com.google.dagger:dagger-android-processor:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android_support: String = "com.google.dagger:dagger-android-support:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_android: String = "com.google.dagger:dagger-android:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
      Versions.com_google_dagger

  /**
   * https://github.com/google/dagger
   */
  const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

  /**
   * https://github.com/square/retrofit
   */
  const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit
   */
  const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit
   */
  const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  /**
   * https://github.com/ReactiveX/RxJava
   */
  const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

  /**
   * http://jcp.org/aboutJava/communityprocess/final/jsr250/index.html
   */
  const val jsr250_api: String = "javax.annotation:jsr250-api:" + Versions.jsr250_api

  /**
   * http://junit.org
   */
  const val junit_junit: String = "junit:junit:" + Versions.junit_junit

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_annotation_processing_gradle: String =
      "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_scripting_compiler_embeddable: String =
      "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://github.com/Kotlin/kotlinx.coroutines
   */
  const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
      Versions.kotlinx_coroutines_core
}
