import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val `annotation`: String = "androidx.annotation:annotation:_"

    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val core_testing: String = "androidx.arch.core:core-testing:_"

    public const val biometric: String = "androidx.biometric:biometric:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    public const val databinding_common: String = "androidx.databinding:databinding-common:_"

    public const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    public const val databinding_ktx: String = "androidx.databinding:databinding-ktx:_"

    public const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    public const val viewbinding: String = "androidx.databinding:viewbinding:_"

    public const val fragment_ktx: String = "androidx.fragment:fragment-ktx:_"

    public const val fragment_testing: String = "androidx.fragment:fragment-testing:_"

    public const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:_"

    public const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:_"

    public const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val androidx_media_media: String = "androidx.media:media:_"

    public const val navigation_dynamic_features_fragment: String =
            "androidx.navigation:navigation-dynamic-features-fragment:_"

    public const val navigation_fragment_ktx: String =
            "androidx.navigation:navigation-fragment-ktx:_"

    public const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:_"

    public const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:_"

    public const val recyclerview: String = "androidx.recyclerview:recyclerview:_"

    public const val room_compiler: String = "androidx.room:room-compiler:_"

    public const val room_ktx: String = "androidx.room:room-ktx:_"

    public const val room_runtime: String = "androidx.room:room-runtime:_"

    public const val room_rxjava2: String = "androidx.room:room-rxjava2:_"

    public const val room_testing: String = "androidx.room:room-testing:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val espresso_intents: String = "androidx.test.espresso:espresso-intents:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val junit_ktx: String = "androidx.test.ext:junit-ktx:_"

    public const val uiautomator: String = "androidx.test.uiautomator:uiautomator:_"

    public const val androidx_test_rules: String = "androidx.test:rules:_"

    public const val androidx_test_runner: String = "androidx.test:runner:_"

    public const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:_"

    public const val au_com_dius_pact_consumer_junit: String = "au.com.dius.pact.consumer:junit:_"

    public const val au_com_dius_pact_gradle_plugin: String =
            "au.com.dius.pact:au.com.dius.pact.gradle.plugin:_"

    public const val logback_classic: String = "ch.qos.logback:logback-classic:_"

    public const val multidex: String = "com.android.support:multidex:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    public const val stetho: String = "com.facebook.stetho:stetho:_"

    public const val glide: String = "com.github.bumptech.glide:glide:_"

    public const val exoplayer_core: String = "com.google.android.exoplayer:exoplayer-core:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val com_google_android_play_core: String = "com.google.android.play:core:_"

    public const val gson: String = "com.google.code.gson:gson:_"

    public const val dagger: String = "com.google.dagger:dagger:_"

    public const val dagger_android: String = "com.google.dagger:dagger-android:_"

    public const val dagger_android_processor: String =
            "com.google.dagger:dagger-android-processor:_"

    public const val dagger_android_support: String = "com.google.dagger:dagger-android-support:_"

    public const val dagger_compiler: String = "com.google.dagger:dagger-compiler:_"

    public const val firebase_analytics_ktx: String = "com.google.firebase:firebase-analytics-ktx:_"

    public const val firebase_bom: String = "com.google.firebase:firebase-bom:_"

    public const val firebase_crashlytics_gradle: String =
            "com.google.firebase:firebase-crashlytics-gradle:_"

    public const val firebase_crashlytics_ktx: String =
            "com.google.firebase:firebase-crashlytics-ktx:_"

    public const val google_services: String = "com.google.gms:google-services:_"

    public const val guava: String = "com.google.guava:guava:_"

    public const val dexmaker_mockito: String = "com.linkedin.dexmaker:dexmaker-mockito:_"

    public const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:_"

    public const val mockwebserver: String = "com.squareup.okhttp3:mockwebserver:_"

    public const val okhttp: String = "com.squareup.okhttp3:okhttp:_"

    public const val okhttp_tls: String = "com.squareup.okhttp3:okhttp-tls:_"

    public const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:_"

    public const val converter_gson: String = "com.squareup.retrofit2:converter-gson:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:_"

    public const val cucumber_android: String = "io.cucumber:cucumber-android:_"

    public const val rxjava: String = "io.reactivex.rxjava2:rxjava:_"

    public const val javax_inject: String = "javax.inject:javax.inject:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val appauth: String = "net.openid:appauth:_"

    public const val org_jacoco_agent: String = "org.jacoco:org.jacoco.agent:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val org_jacoco_core: String = "org.jacoco:org.jacoco.core:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:_"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    public const val mockito_kotlin: String = "org.mockito.kotlin:mockito-kotlin:_"

    public const val mockito_core: String = "org.mockito:mockito-core:_"
}
