/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0"

    const val au_com_dius_pact_consumer_java8: String = "au.com.dius.pact.consumer:java8:4.1.21"

    const val au_com_dius_pact_consumer_junit: String = "au.com.dius.pact.consumer:junit:4.1.21"

    const val adapter_rxjava2: String = "com.squareup.retrofit2:adapter-rxjava2:2.9.0"

    const val converter_gson: String = "com.squareup.retrofit2:converter-gson:2.9.0"

    const val retrofit: String = "com.squareup.retrofit2:retrofit:2.9.0"

    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.5.10"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10"

    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.5.10"

    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:1.5.10"

    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.10"

    const val lifecycle_common_java8: String = "androidx.lifecycle:lifecycle-common-java8:2.3.1"

    const val lifecycle_livedata_ktx: String = "androidx.lifecycle:lifecycle-livedata-ktx:2.3.1"

    const val lifecycle_process: String = "androidx.lifecycle:lifecycle-process:2.3.1"

    const val lifecycle_reactivestreams_ktx: String =
            "androidx.lifecycle:lifecycle-reactivestreams-ktx:2.3.1"

    const val lifecycle_runtime_ktx: String = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"

    const val lifecycle_service: String = "androidx.lifecycle:lifecycle-service:2.3.1"

    const val lifecycle_viewmodel_ktx: String = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"

    const val androidx_multidex_multidex: String = "androidx.multidex:multidex:2.0.0"

    const val multidex_instrumentation: String = "androidx.multidex:multidex-instrumentation:2.0.0"

    const val androidx_test_ext_junit: String = "androidx.test.ext:junit:1.1.2"

    const val junit_ktx: String = "androidx.test.ext:junit-ktx:1.1.2"

    const val dagger: String = "com.google.dagger:dagger:2.35.1"

    const val dagger_android: String = "com.google.dagger:dagger-android:2.35.1"

    const val dagger_android_processor: String = "com.google.dagger:dagger-android-processor:2.35.1"

    const val dagger_android_support: String = "com.google.dagger:dagger-android-support:2.35.1"

    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:2.35.1"

    const val room_compiler: String = "androidx.room:room-compiler:2.3.0"

    const val room_ktx: String = "androidx.room:room-ktx:2.3.0"

    const val room_runtime: String = "androidx.room:room-runtime:2.3.0"

    const val room_rxjava2: String = "androidx.room:room-rxjava2:2.3.0"

    const val room_testing: String = "androidx.room:room-testing:2.3.0"

    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:4.2.1"

    const val com_android_support_multidex: String = "com.android.support:multidex:1.0.3"

    const val androidx_media_media: String = "androidx.media:media:1.3.1"

    const val junit_junit: String = "junit:junit:4.13.2"

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:0.7.0"

    const val au_com_dius_pact_gradle_plugin: String =
            "au.com.dius.pact:au.com.dius.pact.gradle.plugin:4.1.0"

    const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:1.0.0"

    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:2.0.4"

    const val cucumber_android: String = "io.cucumber:cucumber-android:4.8.4"

    const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:2.5.0"

    const val logback_classic: String = "ch.qos.logback:logback-classic:1.2.3"

    const val exoplayer_core: String = "com.google.android.exoplayer:exoplayer-core:2.14.0"

    const val espresso_core: String = "androidx.test.espresso:espresso-core:3.3.0"

    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:1.3.4"

    const val mockito_core: String = "org.mockito:mockito-core:3.11.0"

    const val recyclerview: String = "androidx.recyclerview:recyclerview:1.2.0"

    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:27.2.1"

    const val uiautomator: String = "androidx.test.uiautomator:uiautomator:2.2.0"

    const val viewbinding: String = "androidx.databinding:viewbinding:4.2.1"

    const val annotation: String = "androidx.annotation:annotation:1.1.0"

    const val jsr250_api: String = "javax.annotation:jsr250-api:1.0"

    const val appcompat: String = "androidx.appcompat:appcompat:1.3.0"

    const val cardview: String = "androidx.cardview:cardview:1.0.0"

    const val core_ktx: String = "androidx.core:core-ktx:1.5.0"

    const val material: String = "com.google.android.material:material:1.3.0"

    const val appauth: String = "net.openid:appauth:0.8.1"

    const val rxjava: String = "io.reactivex.rxjava2:rxjava:2.2.21"

    const val stetho: String = "com.facebook.stetho:stetho:1.6.0"

    const val glide: String = "com.github.bumptech.glide:glide:4.12.0"

    const val gson: String = "com.google.code.gson:gson:2.8.7"
}
